name: Docker

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

env:
  REGISTRY: ghcr.io
  BACKEND_IMAGE_NAME: demo-invenioils-backend
  FRONTEND_IMAGE_NAME: demo-invenioils-frontend

jobs:
  build-push:
    name: Publish images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish backend image
        uses: docker/build-push-action@v3
        with:
          context: ./demo-invenioils/
          file: ./demo-invenioils/docker/backend/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.BACKEND_IMAGE_NAME }}:latest

      - name: Build and publish frontend image
        uses: docker/build-push-action@v3
        with:
          context: ./demo-invenioils/
          file: ./demo-invenioils/docker/frontend/Dockerfile
          build-args: |
            BACKEND_BUILT_IMAGE_URL=${{ env.REGISTRY }}/${{ github.repository }}/${{ env.BACKEND_IMAGE_NAME }}:latest
            ENV_NAME=prod
            INVENIO_UI_URL=https://invenioils.web.cern.ch
            INVENIO_REST_ENDPOINTS_BASE_URL=https://invenioils.web.cern.ch/api
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.FRONTEND_IMAGE_NAME }}:latest
